### ISSUE TITLE
Platform of ModFile not exposed

### ISSUE THREAD

**Issue by laundmo** [ClementJ18/mod.io#12]
Thanks for making this, made my life a lot easier.

I needed access to the platform of a ModFile, which is missing for your model.

I added it on my own fork just to be able to access it, but it just exposes the json for now.
https://github.com/laundmo/mod.io/commit/ed5c2530325632467e12f33d2f83fe9ad2588bb0

just thought I'd make you aware

**Comment by laundmo** [comment]
i've added another commit to my fork which fixes the issue that pagination.max() can blow past the total and cause pagination code to loop endlessly

**Comment by ClementJ18** [comment]
Hey, thanks for the fixes, really appreciate it. If you want you can open a PR, if not I'll do it when I have time in the upcoming week and release a new version of the package.

**Comment by ClementJ18** [comment]
Resolved in v0.4.2
