### ISSUE TITLE
Error: More than one .egg-info directory found

### ISSUE THREAD

**Issue by MyNameIsTrez** [ClementJ18/mod.io#3]
After running `<python path>/python.exe -m pip install -U git+https://github.com/ClementJ18/mod.io.git` I kept getting `ERROR: More than one .egg-info directory found in C:\Users\welfj\AppData\Local\Temp\pip-pip-egg-info-e_g3fkh9`.

The issue is caused by setup.py calling the `setup()` function multiple times, which I found due to it being discussed [here](https://bitbucket.org/simongravel/moments/issues/36/cannot-install-moments-using-pip-install).

The reason there are two calls in this repository is because there's one for `setup(name='modio', ...` and one for `setup(name='async_modio', ...`. I'm not sure what the best way to fix this issue is.

**Comment by ClementJ18** [comment]
Gonna have a look this during the week, probably gonna give the library a bit of a shakeup too.

**Comment by ClementJ18** [comment]
v0.3.0 is out, this should fix your issue and it also changes a lot of stuff and adds the new endpoints. Gonna keep looking to upgrade the lib over the next few weeks. In the meantime this issue is resolved so I'm closing it. You can now install the library with `pip install mod.io`
